### ISSUE TITLE
Seed is abending when DB is be seeded.

### ISSUE THREAD

**Issue by mdchafin** [GregFinzer/BedBrigadeNational#238]
[Log20230703.txt](https://github.com/GregFinzer/BedBrigadeNational/files/11940519/Log20230703.txt)

**Comment by GregFinzer** [comment]
Fixed.  Please delete the database and get latest from develop.

**Comment by mdchafin** [comment]
No abend, but no images are displaying.

**Comment by GregFinzer** [comment]
You will need to delete your media directory
